# Generated by Django 5.1.3 on 2026-09-18 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('general_fitness', 'General Fitness')], max_length=30)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=5)),
                ('daily_calories', models.PositiveIntegerField(default=2200)),
                ('macros', models.JSONField(default=dict, help_text="e.g. {'protein': '140g', 'carbs': '220g', 'fats': '55g'}")),
                ('meals', models.JSONField(default=list, help_text='List of meals: breakfast, mid_morning, lunch, evening_snack, dinner')),
                ('trainer_advice', models.TextField(blank=True, default='Stay hydrated, drink at least 3-4 liters of water today.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'day_of_week'],
                'unique_together': {('category', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('1_month', '1 Month Starter'), ('3_months', '3 Months Pro'), ('6_months', '6 Months Elite'), ('annual', 'Annual VIP Legacy')], default='3_months', max_length=50)),
                ('plan_title', models.CharField(default='3 Months Pro', max_length=100)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('total_fee', models.DecimalField(decimal_places=2, default=9999.0, max_digits=10)),
                ('paid_fee', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=3999.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Renewal'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instruction_text', models.TextField()),
                ('scheduled_for_date', models.DateField(help_text='Scheduled date (e.g. one day in advance)')),
                ('is_advance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions_received', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=5)),
                ('category', models.CharField(choices=[('general', 'General Fitness'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain / Hypertrophy')], default='general', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('focus_muscle', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('exercises', models.JSONField(default=list, help_text='List of exercises with sets, reps, and tips')),
                ('trainer_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
    ]
