# Generated by Django 5.1.3 on 2026-09-18 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id_dietplan_membership_trainerinstruction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('category', models.CharField(choices=[('Workout Room', 'Workout Room / Floor'), ('Leg Equipment', 'Leg Equipment'), ('Cardio Zone', 'Cardio Zone'), ('Upper Body', 'Upper Body'), ('CrossFit & Functional', 'CrossFit & Functional'), ('General', 'General Gym Lounge')], default='Workout Room', max_length=50)),
                ('tag', models.CharField(blank=True, default='Strength Training', max_length=50)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('media_url', models.URLField(blank=True, help_text='Direct URL or YouTube/Cloud link for video/image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
