# Generated by Django 5.1.3 on 2026-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gallerymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_pin',
            field=models.CharField(blank=True, default='198426', help_text='Admin 2-Step Verification PIN / OTP', max_length=10),
        ),
    ]
