# Generated by Django 5.1.3 on 2026-09-18 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_two_factor_pin_adminotpcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general_fitness', 'General Fitness'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('guidance_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDailyWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.CharField(default='06:30 AM', max_length=20)),
                ('end_time', models.CharField(default='07:45 AM', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
