# Generated by Django 5.1.3 on 2026-09-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_categoryguidance_memberdailyworkoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='fitness_category',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_category',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='category',
            field=models.CharField(choices=[('general_fitness', 'General Fitness'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain')], default='general_fitness', max_length=30),
        ),
    ]
