# Generated by Django 5.1.3 on 2026-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_membership_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Debit / Credit)'), ('upi', 'UPI (GPay / PhonePe / Paytm)'), ('bank_transfer', 'Bank Transfer (NEFT / IMPS)')], default='upi', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='has_medical_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='injuries_surgeries',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_condition_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='fitness_category',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('general_fitness', 'General Fitness'), ('strength_training', 'Strength Training'), ('muscle_gain', 'Muscle Gain'), ('body_transformation', 'Body Transformation')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, default=4999.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan_name',
            field=models.CharField(choices=[('1_month', '1 Month Starter'), ('3_months', '3 Months Pro'), ('6_months', '6 Months Elite'), ('12_months', '12 Months Annual VIP')], default='3_months', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=4999.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='fitness_category',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('general_fitness', 'General Fitness'), ('strength_training', 'Strength Training'), ('muscle_gain', 'Muscle Gain'), ('body_transformation', 'Body Transformation')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
